// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/echo.proto
package service

import (
	"testing"

	"golang.org/x/net/context"

	pb "github.com/gomeet-examples/svc-echo/pb"
)

func TestVersion(t *testing.T) {
	server := newEchoServer()

	versionResponse, err := server.Version(context.Background(), &pb.EmptyMessage{})

	if err != nil {
		t.Errorf("Error on calling Version: %v", err)
	}

	if versionResponse.GetName() != name {
		t.Errorf("Expected \"%s\" in Name field, got \"%s\"", name, versionResponse.GetName())
	}

	if versionResponse.GetVersion() != version {
		t.Errorf("Expected \"%s\" in Version field, got \"%s\"", version, versionResponse.GetName())
	}
}
