// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/echo.proto
// to extend the echoHTTPController struct use a new file
package service

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	log "github.com/sirupsen/logrus"

	pb "github.com/gomeet-examples/svc-echo/pb"
)

type echoHTTPController struct{}

func newEchoHTTPController() *echoHTTPController {
	return new(echoHTTPController)
}

func (s echoHTTPController) Status(w http.ResponseWriter, r *http.Request) {
	log.Info("echoHTTPController.Status")
	fmt.Fprintf(w, "OK")
}

func (s echoHTTPController) Swagger(w http.ResponseWriter, r *http.Request) {
	log.Info("echoHTTPController.Swagger")
	w.Header().Set("Content-Type", "application/json")
	io.Copy(w, strings.NewReader(pb.Swagger))
}

func (s echoHTTPController) Version(w http.ResponseWriter, r *http.Request) {
	log.Info("echoHTTPController.Version")
	v := pb.VersionResponse{
		Name:    name,
		Version: version,
	}
	output, err := json.Marshal(v)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Write(output)
}
