// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/echo.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/echo.proto

It has these top-level messages:
	EmptyMessage
	VersionResponse
	ServiceStatus
	ServicesStatusList
	EchoRequest
	EchoResponse
*/
package pb

import regexp "regexp"
import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/gomeet/go-proto-gomeetfaker"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EmptyMessage) Validate() error {
	return nil
}
func (this *VersionResponse) Validate() error {
	return nil
}
func (this *ServiceStatus) Validate() error {
	return nil
}
func (this *ServicesStatusList) Validate() error {
	for _, item := range this.Services {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Services", err)
			}
		}
	}
	return nil
}

var _regex_EchoRequest_Uuid = regexp.MustCompile("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$")

func (this *EchoRequest) Validate() error {
	if !_regex_EchoRequest_Uuid.MatchString(this.Uuid) {
		return go_proto_validators.FieldError("Uuid", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}$"`, this.Uuid))
	}
	if !(len(this.Content) > 3) {
		return go_proto_validators.FieldError("Content", fmt.Errorf(`value '%v' must length be greater than '3'`, this.Content))
	}
	return nil
}
func (this *EchoResponse) Validate() error {
	return nil
}
