// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/echo.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/echo.proto

It has these top-level messages:
	EmptyMessage
	VersionResponse
	ServiceStatus
	ServicesStatusList
	EchoRequest
	EchoResponse
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/gomeet/go-proto-gomeetfaker"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ServiceStatus_Status int32

const (
	ServiceStatus_OK          ServiceStatus_Status = 0
	ServiceStatus_UNAVAILABLE ServiceStatus_Status = 1
)

var ServiceStatus_Status_name = map[int32]string{
	0: "OK",
	1: "UNAVAILABLE",
}
var ServiceStatus_Status_value = map[string]int32{
	"OK":          0,
	"UNAVAILABLE": 1,
}

func (x ServiceStatus_Status) String() string {
	return proto.EnumName(ServiceStatus_Status_name, int32(x))
}
func (ServiceStatus_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptorEcho, []int{2, 0} }

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptorEcho, []int{0} }

// VersionMessage represents a version message
type VersionResponse struct {
	// Id represents the message identifier.
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptorEcho, []int{1} }

func (m *VersionResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// SeviceStatus represents a sub services status message
type ServiceStatus struct {
	Name    string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status  ServiceStatus_Status `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.gomeetexamples.echo.ServiceStatus_Status" json:"status,omitempty"`
	EMsg    string               `protobuf:"bytes,4,opt,name=e_msg,json=eMsg,proto3" json:"e_msg,omitempty"`
}

func (m *ServiceStatus) Reset()                    { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string            { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()               {}
func (*ServiceStatus) Descriptor() ([]byte, []int) { return fileDescriptorEcho, []int{2} }

func (m *ServiceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceStatus) GetStatus() ServiceStatus_Status {
	if m != nil {
		return m.Status
	}
	return ServiceStatus_OK
}

func (m *ServiceStatus) GetEMsg() string {
	if m != nil {
		return m.EMsg
	}
	return ""
}

// ServicesStatusList is the sub services status list
type ServicesStatusList struct {
	Services []*ServiceStatus `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServicesStatusList) Reset()                    { *m = ServicesStatusList{} }
func (m *ServicesStatusList) String() string            { return proto.CompactTextString(m) }
func (*ServicesStatusList) ProtoMessage()               {}
func (*ServicesStatusList) Descriptor() ([]byte, []int) { return fileDescriptorEcho, []int{3} }

func (m *ServicesStatusList) GetServices() []*ServiceStatus {
	if m != nil {
		return m.Services
	}
	return nil
}

// EchoRequest represents a simple message sent to the Echo service.
type EchoRequest struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptorEcho, []int{4} }

func (m *EchoRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EchoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// EchoResponse represents a simple message that the Echo service return.
type EchoResponse struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptorEcho, []int{5} }

func (m *EchoResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EchoResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "grpc.gomeetexamples.echo.EmptyMessage")
	proto.RegisterType((*VersionResponse)(nil), "grpc.gomeetexamples.echo.VersionResponse")
	proto.RegisterType((*ServiceStatus)(nil), "grpc.gomeetexamples.echo.ServiceStatus")
	proto.RegisterType((*ServicesStatusList)(nil), "grpc.gomeetexamples.echo.ServicesStatusList")
	proto.RegisterType((*EchoRequest)(nil), "grpc.gomeetexamples.echo.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "grpc.gomeetexamples.echo.EchoResponse")
	proto.RegisterEnum("grpc.gomeetexamples.echo.ServiceStatus_Status", ServiceStatus_Status_name, ServiceStatus_Status_value)
}
func (this *EmptyMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EmptyMessage)
	if !ok {
		that2, ok := that.(EmptyMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *VersionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionResponse)
	if !ok {
		that2, ok := that.(VersionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	return true
}
func (this *ServiceStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServiceStatus)
	if !ok {
		that2, ok := that.(ServiceStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.EMsg != that1.EMsg {
		return false
	}
	return true
}
func (this *ServicesStatusList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServicesStatusList)
	if !ok {
		that2, ok := that.(ServicesStatusList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Services) != len(that1.Services) {
		return false
	}
	for i := range this.Services {
		if !this.Services[i].Equal(that1.Services[i]) {
			return false
		}
	}
	return true
}
func (this *EchoRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EchoRequest)
	if !ok {
		that2, ok := that.(EchoRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Content != that1.Content {
		return false
	}
	return true
}
func (this *EchoResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EchoResponse)
	if !ok {
		that2, ok := that.(EchoResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Content != that1.Content {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Echo service

type EchoClient interface {
	// Version method receives no paramaters and returns a version message.
	Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error)
	// Echo method receives a simple message and returns it.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoClient struct {
	cc *grpc.ClientConn
}

func NewEchoClient(cc *grpc.ClientConn) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.echo.Echo/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error) {
	out := new(ServicesStatusList)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.echo.Echo/ServicesStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.echo.Echo/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Echo service

type EchoServer interface {
	// Version method receives no paramaters and returns a version message.
	Version(context.Context, *EmptyMessage) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(context.Context, *EmptyMessage) (*ServicesStatusList, error)
	// Echo method receives a simple message and returns it.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterEchoServer(s *grpc.Server, srv EchoServer) {
	s.RegisterService(&_Echo_serviceDesc, srv)
}

func _Echo_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.echo.Echo/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Version(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_ServicesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).ServicesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.echo.Echo/ServicesStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).ServicesStatus(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.echo.Echo/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Echo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gomeetexamples.echo.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Echo_Version_Handler,
		},
		{
			MethodName: "ServicesStatus",
			Handler:    _Echo_ServicesStatus_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/echo.proto",
}

func NewPopulatedEmptyMessage(r randyEcho, easy bool) *EmptyMessage {
	this := &EmptyMessage{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedVersionResponse(r randyEcho, easy bool) *VersionResponse {
	this := &VersionResponse{}
	this.Name = string(randStringEcho(r))
	this.Version = string(randStringEcho(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServiceStatus(r randyEcho, easy bool) *ServiceStatus {
	this := &ServiceStatus{}
	this.Name = string(randStringEcho(r))
	this.Version = string(randStringEcho(r))
	this.Status = ServiceStatus_Status([]int32{0, 1}[r.Intn(2)])
	this.EMsg = string(randStringEcho(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServicesStatusList(r randyEcho, easy bool) *ServicesStatusList {
	this := &ServicesStatusList{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Services = make([]*ServiceStatus, v1)
		for i := 0; i < v1; i++ {
			this.Services[i] = NewPopulatedServiceStatus(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEchoRequest(r randyEcho, easy bool) *EchoRequest {
	this := &EchoRequest{}
	this.Uuid = string(randStringEcho(r))
	this.Content = string(randStringEcho(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEchoResponse(r randyEcho, easy bool) *EchoResponse {
	this := &EchoResponse{}
	this.Uuid = string(randStringEcho(r))
	this.Content = string(randStringEcho(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyEcho interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneEcho(r randyEcho) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringEcho(r randyEcho) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneEcho(r)
	}
	return string(tmps)
}
func randUnrecognizedEcho(r randyEcho, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldEcho(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldEcho(dAtA []byte, r randyEcho, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateEcho(dAtA, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		dAtA = encodeVarintPopulateEcho(dAtA, uint64(v3))
	case 1:
		dAtA = encodeVarintPopulateEcho(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateEcho(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateEcho(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateEcho(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateEcho(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}

func init() { proto.RegisterFile("pb/echo.proto", fileDescriptorEcho) }

var fileDescriptorEcho = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xc6, 0x75, 0x9d, 0x76, 0xfa, 0xfb, 0xcd, 0xa6, 0x26, 0x8a, 0x42, 0x30, 0xa2, 0xa4,
	0x15, 0xf1, 0xa8, 0x01, 0x21, 0x04, 0xab, 0x04, 0x05, 0x84, 0x48, 0xa0, 0x72, 0x44, 0x24, 0xba,
	0x41, 0xb6, 0x3b, 0x75, 0xac, 0xc6, 0x1e, 0xe3, 0x19, 0xbb, 0xb0, 0xed, 0x86, 0x07, 0xe0, 0x0d,
	0x58, 0xb1, 0xc8, 0x03, 0xf4, 0x19, 0xb2, 0x65, 0xc7, 0x8e, 0x8a, 0x77, 0x80, 0x25, 0xca, 0x78,
	0xdc, 0x26, 0x40, 0x68, 0x25, 0x58, 0x79, 0xe6, 0xde, 0x73, 0xee, 0xb9, 0x33, 0xe7, 0x7a, 0xe0,
	0x4a, 0xe4, 0x60, 0xe2, 0xf6, 0xa9, 0x19, 0xc5, 0x94, 0x53, 0xa4, 0x7b, 0x71, 0xe4, 0x9a, 0x1e,
	0x0d, 0x08, 0xe1, 0xe4, 0x8d, 0x1d, 0x44, 0x03, 0xc2, 0xcc, 0x71, 0xbe, 0x58, 0xf2, 0x28, 0xf5,
	0x06, 0x04, 0xdb, 0x91, 0x8f, 0xed, 0x30, 0xa4, 0xdc, 0xe6, 0x3e, 0x0d, 0x59, 0xc6, 0x2b, 0xde,
	0xf5, 0x7c, 0xde, 0x4f, 0x1c, 0xd3, 0xa5, 0x01, 0x0e, 0x8e, 0x7c, 0x7e, 0x48, 0x8f, 0xb0, 0x47,
	0x6b, 0x22, 0x59, 0x4b, 0xed, 0x81, 0xbf, 0x6f, 0x73, 0x1a, 0x33, 0x7c, 0xb6, 0x94, 0xbc, 0x7b,
	0x13, 0xbc, 0x4c, 0xf5, 0x9c, 0x96, 0xed, 0x0f, 0xec, 0x43, 0x12, 0xe3, 0x89, 0xb5, 0x64, 0xd6,
	0xa6, 0x98, 0x1e, 0xc5, 0x22, 0xec, 0x24, 0x07, 0x62, 0x27, 0x36, 0x62, 0x95, 0xc1, 0x8d, 0x55,
	0xb8, 0xdc, 0x0a, 0x22, 0xfe, 0xb6, 0x43, 0x18, 0xb3, 0x3d, 0x62, 0x74, 0xe1, 0x5a, 0x8f, 0xc4,
	0xcc, 0xa7, 0xa1, 0x45, 0x58, 0x44, 0x43, 0x46, 0x50, 0x09, 0xaa, 0xa1, 0x1d, 0x10, 0x1d, 0x54,
	0x40, 0x75, 0xb1, 0xb9, 0x30, 0x1a, 0x6a, 0xea, 0xb6, 0xb2, 0x0e, 0x2c, 0x11, 0x45, 0x06, 0x2c,
	0xa4, 0x19, 0x41, 0x57, 0x26, 0x01, 0x3a, 0xb0, 0xf2, 0x84, 0xf1, 0x19, 0xc0, 0x95, 0x2e, 0x89,
	0x53, 0xdf, 0x25, 0x5d, 0x6e, 0xf3, 0x84, 0xfd, 0x7d, 0x4d, 0xf4, 0x08, 0x6a, 0x4c, 0xd4, 0xd2,
	0xe7, 0x2a, 0xa0, 0xba, 0x5a, 0x37, 0xcd, 0x59, 0x16, 0x99, 0x53, 0xd2, 0x66, 0xf6, 0xb1, 0x24,
	0x1b, 0x95, 0xe0, 0x3c, 0x79, 0x15, 0x30, 0x4f, 0x57, 0x85, 0x52, 0x61, 0x34, 0xd4, 0xe6, 0x4e,
	0x00, 0xb0, 0x54, 0xd2, 0x61, 0x9e, 0x71, 0x0d, 0x6a, 0xb2, 0x63, 0x0d, 0x2a, 0xcf, 0x9f, 0xae,
	0xff, 0x87, 0xd6, 0xe0, 0xd2, 0x8b, 0x67, 0x8d, 0x5e, 0xe3, 0x49, 0xbb, 0xd1, 0x6c, 0xb7, 0xd6,
	0x81, 0xf1, 0x12, 0x22, 0x29, 0xc0, 0x32, 0x68, 0xdb, 0x67, 0x1c, 0x3d, 0x84, 0x0b, 0x4c, 0x46,
	0x75, 0x50, 0x99, 0xab, 0x2e, 0xd5, 0x6f, 0x5e, 0xb2, 0x41, 0xeb, 0x8c, 0x68, 0x58, 0x70, 0xa9,
	0xe5, 0xf6, 0xa9, 0x45, 0x5e, 0x27, 0x84, 0x71, 0x54, 0x86, 0x6a, 0x92, 0xf8, 0xfb, 0xf2, 0xd2,
	0xe0, 0x68, 0xa8, 0x69, 0x48, 0x45, 0x4a, 0xef, 0x8e, 0x25, 0xe2, 0xe8, 0x3a, 0x2c, 0xb8, 0x34,
	0xe4, 0x24, 0xe4, 0xf2, 0xda, 0x16, 0x47, 0x43, 0x6d, 0xfe, 0x18, 0x28, 0xbb, 0xc0, 0xca, 0x33,
	0x46, 0x17, 0x2e, 0x67, 0x35, 0xa5, 0xbb, 0xff, 0xa2, 0x68, 0xfd, 0x9b, 0x02, 0xd5, 0x71, 0x55,
	0x94, 0xc0, 0x82, 0x1c, 0x1f, 0xb4, 0x39, 0xfb, 0xbc, 0x93, 0x13, 0x57, 0xdc, 0x9a, 0x8d, 0xfb,
	0x69, 0x12, 0x8d, 0x8d, 0xe3, 0x4f, 0x5f, 0xdf, 0x2b, 0xff, 0xa3, 0x35, 0xf1, 0xb7, 0xa5, 0x3b,
	0x38, 0x1f, 0x86, 0x77, 0x00, 0xae, 0x4e, 0x9b, 0x70, 0x69, 0xf9, 0x5b, 0x17, 0xda, 0x32, 0x61,
	0xab, 0x71, 0x55, 0x74, 0x70, 0x05, 0x6d, 0xe4, 0x1d, 0xe4, 0x5e, 0x61, 0x39, 0x4e, 0xa1, 0xbc,
	0x88, 0x1b, 0x7f, 0x90, 0x3f, 0xb7, 0xb4, 0xb8, 0x79, 0x11, 0x6c, 0xfa, 0xe4, 0xc6, 0x72, 0xae,
	0x3b, 0x86, 0xdc, 0x07, 0xdb, 0xcd, 0xbd, 0xef, 0x5f, 0xca, 0xe0, 0xe3, 0x69, 0x19, 0x9c, 0x9c,
	0x96, 0x01, 0x2c, 0xba, 0x34, 0xf8, 0x6d, 0xb1, 0x74, 0x67, 0x6f, 0xeb, 0x97, 0x27, 0xa5, 0x96,
	0x63, 0x30, 0x4b, 0xdd, 0xda, 0x18, 0x87, 0x23, 0xe7, 0x41, 0xe4, 0x7c, 0x50, 0xd4, 0xc7, 0x9d,
	0xdd, 0xa6, 0xa3, 0x89, 0x27, 0xe2, 0xf6, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x75, 0x7a,
	0x2a, 0x0c, 0x05, 0x00, 0x00,
}
